name = "Readmes"
uuid = "8a3d26a3-cc34-4050-9c94-996386f82101"
version = "1.0.0-DEV"
authors = ["Frames White <me@oxinabox.net> and contributors"]

[compat]
ReferenceTests = "0.9,0.10.4"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"

[targets]
test = ["Test", "ReferenceTests"]
