name: regenerate_readme
on: [push, pull_request]
jobs:
  regen:
    name: "Regenerate The README.md"
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.10'
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Generate README.md
        run: julia --color=yes --project=docs/ -e 'using Readmes; generate_readme()'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerate README.md
